### ISSUE TITLE
Getting random file already closed error

### ISSUE THREAD

**Issue by v-pratap** [cloudprober/cloudprober#738] opened 2024-05-03 11:00 UTC
**Describe the bug**
We have deployed the continuous streaming of stdout and stderr in external once probe mode. In few deployments we are getting a lot of errors :
```
Error reading from stderr: read |0: file already closed
Error reading from stdout: read |0: file already closed
```

The error doesn't follow any time pattern.
![Screenshot 2024-05-03 at 4 21 53 PM](https://github.com/cloudprober/cloudprober/assets/83967398/920e7143-4b67-44ab-94cd-c93a62605185)

The cloudprober configuration is : 
```
  {{ $workload_name := "TEST-00"}}
  probe {
    name: "{{$workload_name}}"
    type: EXTERNAL
    targets { dummy_targets {} }
    external_probe {
      mode: ONCE
      command: "......."
    interval_msec: 60000
    timeout_msec:  60000
  }
```

The average time to complete the command execution is around 1000 msec.

**Cloudprober Version**
Latest version.

**To Reproduce**
We are getting this error very frequently with above cloudprober configuration. 

**Additional Context**
Also I want to understand when will this error logged, once the command execution completes and it closes its stdout and stderr?

**Comment by manugarg** [comment] 2024-05-03 17:16
@v-pratap Are you running the latest code? This error was fixed in:
https://github.com/cloudprober/cloudprober/commit/2b2695e98fbb35c699786de544383a7410ea644a

**Comment by v-pratap** [comment] 2024-05-03 17:31
Hi @manugarg,
Yes I am using the latest code : 
<img width="591" alt="Screenshot 2024-05-03 at 11 00 30 PM" src="https://github.com/cloudprober/cloudprober/assets/83967398/99c3a727-99fb-4a0c-9a4a-fea658a1949b">

**Comment by manugarg** [comment] 2024-05-03 17:35
Can you post the full error message. It will have the code line logging this.

**Comment by v-pratap** [comment] 2024-05-03 17:48
There is nothing else than that : 
<img width="830" alt="Screenshot 2024-05-03 at 11 17 52 PM" src="https://github.com/cloudprober/cloudprober/assets/83967398/caa1724d-f457-41c1-8b87-54be3017329e">

**Comment by manugarg** [comment] 2024-05-03 18:05
That's weird. GCP log entry should be complete. We even have a test for it:
https://github.com/cloudprober/cloudprober/blob/896b8fd68e6ca6538780c48be6b36e5f16f47fdb/logger/logger_test.go#L416

I don't have access to any GCP account right now, but can you please use some other interface (kubectl logs, docker logs) to access stderr logs. You can try running it locally also if you've access.

**Comment by manugarg** [comment] 2024-05-03 18:08
Oh if you're using BBMC setup, logs can be either in /tmp/cloudprober.* files or journalctl.

Also, in your first screenshot, I see errors coming from different locations. If you limit to one location, you'll see a more useful pattern.

**Comment by manugarg** [comment] 2024-05-04 02:29
I could reproduce it after running the probe for a while. I got it approximately once in 7-10 attempts. This is more of a random log line, caused by pipe reading failing in different places when external process exits. 

https://github.com/cloudprober/cloudprober/pull/739 should fix it.

**Closed** 2024-05-06 15:27 UTC
Labels: bug
