### ISSUE TITLE
Can't receive response body if request body included

### ISSUE THREAD

**Issue by dlwogus5038** [cloudprober/cloudprober#407] opened 2023-06-16 02:40 UTC
**Describe the bug**
Can't receive response body if request body included

**Cloudprober Version**
0.12.7-1.el7

**To Reproduce**
1. Deploy HTTPS python(`v3.6.8`) server for testing in CentOS 7
    ```python
    import http.server
    import ssl
    import socketserver
    
    context = ssl.SSLContext(ssl.PROTOCOL_TLS_SERVER)
    context.load_cert_chain("cert.pem") # 'openssl req -new -x509 -keyout cert.pem -out cert.pem -days 365 -nodes'
    
    server_address = ('0.0.0.0', 29201)
    request_body = b''
    
    class MyHTTP(http.server.BaseHTTPRequestHandler):
      def do_GET(self):
          # Print the entire request headers
          print(str(self.headers))
          if 'Content-Length' in self.headers:
              # Get request body
              request_body = self.rfile.read(int(self.headers.get('Content-Length')))
              print(request_body)
          # Using HTTP/1.1
          self.protocol_version = 'HTTP/1.1'
          self.send_response(200)
          self.send_header('Content-Type', 'application/json; charset=utf-8')
          self.send_header('Content-Length', len(request_body))
          self.end_headers()
          # Add response body
          self.wfile.write(request_body)
    
    handler = MyHTTP
    with socketserver.TCPServer(server_address, handler) as httpd:
      httpd.socket = context.wrap_socket(httpd.socket, server_side=True)
      httpd.serve_forever()
    ```
2. Add `body` to `cloudprober.cfg`
    ```yaml
    probe {
      name: "test"
      type: HTTP
      targets {
        host_names: "localhost"
      }
    
      interval_msec: 60000 # 60s
      timeout_msec: 1000 # 1s
    
      http_probe {
        relative_url: "/xxxx/_search"
        port: 29201
        protocol: HTTPS
        headers: {
          name: "Authorization"
          value: "Basic {Basic_Auth_Key}"
        }
        body: "{\"size\":1,\"query\":{\"bool\":{\"must\":[{\"range\":{\"@timestamp\":{\"time_zone\":\"+09:00\",\"gte\":\"now-2m\",\"lte\":\"now\"}}}]}}}"
        keep_alive: true
        tls_config {
          disable_cert_validation: true
        }
      }
    
      validator {
        name: "status_code_2xx"
        http_validator {
          success_status_codes: "200-299"
        }
      }
    }
    ```
3. Check python server output results
    ```
    Host: localhost:29201
    User-Agent: Go-http-client/1.1
    Content-Length: 113
    Authorization: Basic {Basic_Auth_Key}
    Content-Type: application/json
    Accept-Encoding: gzip
    
    
    b'{"size":1,"query":{"bool":{"must":[{"range":{"@timestamp":{"time_zone":"+09:00","gte":"now-2m","lte":"now"}}}]}}}'
    127.0.0.1 - - [15/Jun/2023 19:34:42] "GET /xxxx/_search HTTP/1.1" 200 -
    ----------------------------------------
    Exception happened during processing of request from ('127.0.0.1', 38030)
    Traceback (most recent call last):
      File "/usr/lib64/python3.6/socketserver.py", line 320, in _handle_request_noblock
        self.process_request(request, client_address)
      File "/usr/lib64/python3.6/socketserver.py", line 351, in process_request
        self.finish_request(request, client_address)
      File "/usr/lib64/python3.6/socketserver.py", line 364, in finish_request
        self.RequestHandlerClass(request, client_address, self)
      File "/usr/lib64/python3.6/socketserver.py", line 724, in __init__
        self.handle()
      File "/usr/lib64/python3.6/http/server.py", line 418, in handle
        self.handle_one_request()
      File "/usr/lib64/python3.6/http/server.py", line 406, in handle_one_request
        method()
      File "https_server.py", line 22, in do_GET
        self.wfile.write(request_body)
      File "/usr/lib64/python3.6/socketserver.py", line 803, in write
        self._sock.sendall(b)
      File "/usr/lib64/python3.6/ssl.py", line 934, in sendall
        v = self.send(byte_view[count:])
      File "/usr/lib64/python3.6/ssl.py", line 903, in send
        return self._sslobj.write(data)
      File "/usr/lib64/python3.6/ssl.py", line 601, in write
        return self._sslobj.write(data)
    BrokenPipeError: [Errno 32] Broken pipe
    ----------------------------------------
    ```
    - BrokenPipeError occurs here
4. Check cloudprober `/metrics` page
    ```
    #TYPE total counter
    total{ptype="http",probe="test",dst="localhost"} 957 1686882642687
    #TYPE success counter
    success{ptype="http",probe="test",dst="localhost"} 0 1686882642687
    #TYPE latency counter
    latency{ptype="http",probe="test",dst="localhost"} 0.000 1686882642687
    #TYPE timeouts counter
    timeouts{ptype="http",probe="test",dst="localhost"} 0 1686882642687
    #TYPE connect_event counter
    connect_event{ptype="http",probe="test",dst="localhost"} 957 1686882642687
    #TYPE validation_failure counter
    validation_failure{ptype="http",probe="test",dst="localhost",validator="status_code_2xx"} 0 1686882642687
    #TYPE hostname gauge
    hostname{ptype="sysvars",probe="sysvars",val="xxxxx"} 1 1686882652688
    #TYPE start_timestamp gauge
    start_timestamp{ptype="sysvars",probe="sysvars",val="1686825282"} 1 1686882652688
    #TYPE version gauge
    version{ptype="sysvars",probe="sysvars",val=""} 1 1686882652688
    #TYPE cpu_usage_msec counter
    cpu_usage_msec{ptype="sysvars",probe="sysvars"} 18014.019 1686882652688
    #TYPE uptime_msec counter
    uptime_msec{ptype="sysvars",probe="sysvars"} 57370112.118 1686882652688
    #TYPE gc_time_msec counter
    gc_time_msec{ptype="sysvars",probe="sysvars"} 113.909 1686882652688
    #TYPE mallocs counter
    mallocs{ptype="sysvars",probe="sysvars"} 1334910 1686882652688
    #TYPE frees counter
    frees{ptype="sysvars",probe="sysvars"} 1318029 1686882652688
    #TYPE goroutines gauge
    goroutines{ptype="sysvars",probe="sysvars"} 15 1686882652688
    #TYPE mem_stats_sys_bytes gauge
    mem_stats_sys_bytes{ptype="sysvars",probe="sysvars"} 29209864 1686882652688
    ```
    - `resp_code` and `ssl_earliest_cert_expiry_sec ` do not exist

**Additional context**
If i remove `body` from `cloudprober.cfg`, i can receive response body

- python server output results
    ```
    Host: localhost:29201
    User-Agent: Go-http-client/1.1
    Content-Length: 113
    Authorization: Basic {Basic_Auth_Key}
    Content-Type: application/json
    Accept-Encoding: gzip
    
    
    b'{"size":1,"query":{"bool":{"must":[{"range":{"@timestamp":{"time_zone":"+09:00","gte":"now-2m","lte":"now"}}}]}}}'
    127.0.0.1 - - [15/Jun/2023 19:34:42] "GET /xxxx/_search HTTP/1.1" 200 -
    ```
- `/metrics` page
    ```
    #TYPE total counter
    total{ptype="http",probe="test",dst="localhost"} 1 1686651442855
    #TYPE success counter
    success{ptype="http",probe="test",dst="localhost"} 1 1686651442855
    #TYPE latency counter
    latency{ptype="http",probe="test",dst="localhost"} 380438.021 1686651442855
    #TYPE timeouts counter
    timeouts{ptype="http",probe="test",dst="localhost"} 0 1686651442855
    #TYPE resp_code counter
    resp_code{ptype="http",probe="test",dst="localhost",code="200"} 1 1686651442855
    #TYPE validation_failure counter
    validation_failure{ptype="http",probe="test",dst="localhost",validator="status_code_2xx"} 0 1686651442855
    #TYPE ssl_earliest_cert_expiry_sec gauge
    ssl_earliest_cert_expiry_sec{ptype="http",probe="test",dst="localhost"} 21530496 1686651442855
    #TYPE hostname gauge
    hostname{ptype="sysvars",probe="sysvars",val="xxxxx"} 1 1686651452855
    #TYPE start_timestamp gauge
    start_timestamp{ptype="sysvars",probe="sysvars",val="1686651442"} 1 1686651452855
    #TYPE version gauge
    version{ptype="sysvars",probe="sysvars",val=""} 1 1686651452855
    #TYPE cpu_usage_msec counter
    cpu_usage_msec{ptype="sysvars",probe="sysvars"} 207.332 1686651452855
    #TYPE uptime_msec counter
    uptime_msec{ptype="sysvars",probe="sysvars"} 10110.102 1686651452855
    #TYPE gc_time_msec counter
    gc_time_msec{ptype="sysvars",probe="sysvars"} 1.136 1686651452855
    #TYPE mallocs counter
    mallocs{ptype="sysvars",probe="sysvars"} 76905 1686651452855
    #TYPE frees counter
    frees{ptype="sysvars",probe="sysvars"} 43823 1686651452855
    #TYPE goroutines gauge
    goroutines{ptype="sysvars",probe="sysvars"} 17 1686651452855
    #TYPE mem_stats_sys_bytes gauge
    mem_stats_sys_bytes{ptype="sysvars",probe="sysvars"} 35763464 1686651452855
    ```

**Comment by dlwogus5038** [comment] 2023-06-16 02:43
If i use `curl`, i can receive a response body even if i add a request body

```
curl -vkX GET "https://localhost:29201" \
     -H 'Content-Type: application/json' \
     -H 'Accept-Encoding: gzip' \
     -H 'Authorization: Basic {Basic_Auth_Key}' \
     -d '{"size":1,"query":{"bool":{"must":[{"range":{"@timestamp":{"time_zone":"+09:00","gte":"now-2m","lte":"now"}}}]}}}'
```

**Comment by manugarg** [comment] 2023-06-16 08:34
Thanks a lot for reporting this, @dlwogus5038! I could reproduce the bug. I checked previous versions and it looks like this bug has existed for quite some time now.

After enabling logs with the flag --logtostderr, I found this:
```
W0615 22:52:36.469673   39054 http.go:289] [cloudprober.test] Target:localhost, URL:http://localhost:29201/xxxx/_search, http.doHTTPRequest: Get "http://localhost:29201/xxxx/_search": net/http: HTTP/1.x transport connection broken: http: ContentLength=113 with Body length 226
```
Essentially connection was getting reset because transport encountered error while writing data.
https://cs.opensource.google/go/go/+/master:src/net/http/transport.go;drc=eea26e8e685af0270b10c41c7d8f8de22a520373;l=2073
https://cs.opensource.google/go/go/+/refs/heads/master:src/net/http/transport.go;drc=b7e74678657680a0eb31679623f90b539666c5f4;l=2653

### Root Cause
I found the root cause as well. Here is what's going on:
Go's HTTP data transfer code does this verification that nothing is left unread in the body:
https://cs.opensource.google/go/go/+/master:src/net/http/transfer.go;drc=117fe2e08d2fb385e4febed020b834d2d8e4358a;l=370
```
ncopy, err = t.doBodyCopy(w, io.LimitReader(body, t.ContentLength))
if err != nil {
      return err
}
var nextra int64
nextra, err = t.doBodyCopy(io.Discard, body)
ncopy += nextra
```
It reads the body until EOF/t.ContentLength, and then reads it again until EOF. Which means if you've a non-buffered reader like the one we use for efficiency, it's always going to return the same data again.

There is an easy fix for this that we can implement. I'll also add missing tests for this.

**Comment by manugarg** [comment] 2023-06-16 19:43
#408 contains the fix. However, I'll try to add some tests before submitting it.

**Comment by manugarg** [comment] 2023-06-17 01:12
Added tests in #409. See the test failures here:
https://github.com/cloudprober/cloudprober/actions/runs/5295483818/jobs/9585864458?pr=409

**Comment by manugarg** [comment] 2023-06-17 01:35
@dlwogus5038 I've tested your code and config with the latest changes, and it looks fine. I'll close this issue now. Since this is not a new bug, I'll not do an emergency release, but I'll try to release sooner than usual. Please track the milestone for release.

**Closed by manugarg** 2023-06-17 01:35 UTC
Labels: bug
